navigation component with styles
bonny-art/code-crafters-tp-02 pull request #13
Opened 2024-12-19 16:59 UTC by maistyev

2024-12-19 22:28 UTC, bonny-art requested changes

2024-12-19 22:28 UTC, bonny-art commented on src/css/components/nav.css
> +  font-style: normal;
font-style: normal;
  це і так по замаовчуванню. зайве правило

2024-12-19 22:28 UTC, bonny-art commented on src/css/components/nav.css
> +  .header-nav-list {
через змінну =$place у тебе додасться окремий клас header,  тому правило тобі треба писати .header.nav-list чи .nav-list.header, як тобі більше подобається, тобто що воно приміниться, якщо є 2 класи.

display: flex; - зайве, бо дублює
align-items: center;  gap: 20px; так само

колір зроби через змінну

2024-12-19 22:28 UTC, bonny-art commented on src/css/components/nav.css
> +  .header-nav-list .nav-item::after {
тут так само, краще так .header.nav-list .nav-item::after {

2024-12-19 22:28 UTC, bonny-art commented on src/css/components/nav.css
> +  .header-nav-list .nav-item {
тут так само, краще так .header.nav-list .nav-item {

2024-12-19 22:28 UTC, bonny-art commented on src/css/components/nav.css
> +    background-color: #4dc274;
через змінну колір

2024-12-19 22:28 UTC, bonny-art commented on src/css/components/nav.css
> +  .header-nav-list .nav-item:hover::after {
так само:
.header.nav-list  .nav-item:hover::after {

2024-12-19 22:28 UTC, bonny-art commented on src/css/components/nav.css
> +}
ще одай стилі для футера і. відковідно, змінної =$place = footer

2024-12-19 22:28 UTC, bonny-art commented on src/css/components/nav.css
> +.nav-list {
ябі сюди винесла тільки ті стилі, що загальні для всіх трьох місць розташування. а потім би, по аналогії з .header.nav-list(подивись нижче) зробила бі для мобайл стилі, що стосуються мобайл, для хедера ти вже маєш, і тоді ще для футера.

2024-12-19 22:28 UTC, bonny-art commented on src/css/components/nav.css
> +.header-nav {
думаю, що тут це робити не потрібно. це будуть ховати чи показувати у самому хедері медіаправилом на тег nav. відповідно, якщо він дісплей нан, то і все, що у ньому, не покажеться.

2024-12-19 22:28 UTC, bonny-art commented on src/css/components/nav.css
> +  .header-nav {
тут так само, прибери, церування буде у хедері через тег нав

2024-12-19 22:28 UTC, bonny-art commented on src/css/components/nav.css
> +  justify-content: center;
це зайве
  justify-content: center;

2024-12-19 22:28 UTC, bonny-art commented on src/css/components/nav.css
додай на початку файлу коментар, що підключати його таким чином
<load src="partials/nav.html" place="header" />
варіанти place="header" place="mobile-menu" place="footer"

і потім ці ж значення у якості класів використовуй, як я написала нижче

2024-12-21 12:28 UTC, maistyev commented on src/css/components/nav.css
> +.nav-list {
Виніс сюди однакові стилі для моб меню та футера, оскільки вони схожі, для хедера залишив у медіаправилі

2024-12-21 12:29 UTC, maistyev commented on src/css/components/nav.css
> +  color: #ffffff;
виправлено

2024-12-21 12:29 UTC, maistyev commented on src/css/components/nav.css
> +.header-nav {
прибрав стилі .header-nav
потім додам їх у header.css

2024-12-21 12:30 UTC, maistyev commented on src/css/components/nav.css
> +  .header-nav {
виправлено

2024-12-21 22:22 UTC, bonny-art approved these changes

2024-12-21 22:23 UTC, merged