Header
bonny-art/code-crafters-tp-02 pull request #14
Opened 2024-12-19 21:16 UTC by maistyev

2024-12-19 23:42 UTC, bonny-art requested changes

2024-12-19 23:42 UTC, bonny-art commented on src/partials/header.html
> +      <svg class="burger-button-icon" width="32" height="32">
іконки на мобілці і таблеті різні

через те, що ти тільки розмір змінюєш, у тебе на таблеті іконка не правлиьно розташована
жива сторінка
![image](https://github.com/user-attachments/assets/9d428274-15fa-4f73-b5d6-771b3629a646)

макет
![image](https://github.com/user-attachments/assets/f149fbf2-a94d-4d58-ba86-ae3a86519c14)

2024-12-19 23:42 UTC, bonny-art commented on src/css/components/header.css
> +.header-logo {
перевір іншу стилізацію тексту. у тебе бракує правил

2024-12-19 23:42 UTC, bonny-art commented on src/css/components/header.css
> +  .header-socials {
ці правила будуть в юл. але так розумію що ми це узгодили під час міту сьогодні.  тобі тут не потрібно ніяких класів стосовно сошлз буде звагалі. тільки в хтмл поті передаш відповідне значення змінної

2024-12-19 23:42 UTC, bonny-art commented on src/css/components/header.css
> +    width: 40px;
в даному випадку так не працює, бо інші пропорції. тут треба завантажувати 2 різні іконки. в хтмл нижче подивишся, чому

2024-12-19 23:42 UTC, bonny-art commented on src/partials/header.html
> +    <button class="burger-button">
додай клас чи ід для скрипта

2024-12-20 20:25 UTC, maistyev commented on src/css/components/header.css
> +  padding-top: 20px;
там по фігмі здається падінг від кнопки якраз 20, але чомусь її поля не зовсім корректно показує

2024-12-20 20:26 UTC, maistyev commented on src/partials/header.html
> +      <svg class="burger-button-icon" width="32" height="32">
виправлено
зміщення було більше не від того, що неправильні розміри, а через стандартні стилі кнопки (додаткові падінги). Скинув їх у nav.css, але мабуть є сенс преенести скидання і на глобальний reset.css

2024-12-20 20:26 UTC, maistyev commented on src/css/components/header.css
> +.header-logo {
додав

2024-12-20 20:27 UTC, maistyev commented on src/css/components/header.css
> +  .header-socials {
ці правила тимчасові, чисто щоб "забронювати" місце
як компонент буде готовий піддягну через load

2024-12-20 20:28 UTC, maistyev commented on src/css/components/header.css
> +    width: 40px;
виправлено

2024-12-20 20:29 UTC, maistyev commented on src/partials/header.html
> +    <button class="burger-button">
в скрипті використовується клас .burger-button

2024-12-21 01:15 UTC, bonny-art requested changes

2024-12-21 01:15 UTC, bonny-art commented on src/css/components/header.css
> +  padding-top: 20px;
![image](https://github.com/user-attachments/assets/db7609d8-f40a-4448-85ce-94f0fc63cecf)

ота синя рамка, від якої йде замір - це і є розмір кнопки. от з тим повітрям зверху знизу та зліва. і з тим повітрям вона має розмір 32х32 і саме так вставляється у розмітку. а у тебе зараз від тих 32 на мобілці падінги зроблені. можна, звісно, як казав Косиця, допускати +/- 5 пікселів розбіжності та забити на це....

2024-12-21 01:15 UTC, bonny-art commented on src/partials/header.html
> +    <button class="burger-button">
це не є добре. для js потрібно зробити окремий клас, на якому не буде висіти жодна стилізація. гарна практика в назву класу для скрипта в кінці додати -js.

2024-12-21 01:16 UTC, bonny-art requested changes
На рахунок класу для скрипта прошу виправити. А з вертикальними падингами як сам вирішиш. але для інформації тобі там написала як воно рахується.

2024-12-21 11:43 UTC, maistyev commented on src/partials/header.html
> +    <button class="burger-button">
Ок, але тоді треба буде в js також поправити назву, в гілці mobile-menu

2024-12-21 12:10 UTC, maistyev commented on src/css/components/header.css
> +  padding-top: 20px;
виправив, здається по пікселям +/- рівно

2024-12-21 13:34 UTC, bonny-art approved these changes

2024-12-21 13:34 UTC, merged