Footer
bonny-art/code-crafters-tp-02 pull request #15
Opened 2024-12-19 23:39 UTC by MarynaKip

Footer layout and styles were created

2024-12-20 00:28 UTC, bonny-art requested changes

2024-12-20 00:28 UTC, bonny-art commented on src/css/components/footer.css
> +  padding: 65px 0;
на десктопі падинг 64пікс, а на таблеті інший.

2024-12-20 00:28 UTC, bonny-art commented on src/css/components/footer.css
> +  margin-bottom: 31px;
margin-bottom: 31px;
 чому так, якщо на макеті 32?

2024-12-20 00:28 UTC, bonny-art commented on src/css/components/footer.css
> +  justify-content: space-between;
на таблеті та десктопі відстані між лівою та центральною колонкою та між центарльною та правою мають бути різні

2024-12-20 00:28 UTC, bonny-art commented on src/css/components/footer.css
> +  color: white;
колір через змінну

2024-12-20 00:28 UTC, bonny-art commented on src/css/components/footer.css
> +  letter-spacing: -2%;
це в em нам рекомендували на лекціях визначати

2024-12-20 00:28 UTC, bonny-art commented on src/css/components/footer.css
> +  font-family: Manrope, sans-serif;
тут шрифт зайвий, він успадковується з боді

2024-12-20 00:28 UTC, bonny-art commented on src/css/components/footer.css
> +  font-family: Manrope, sans-serif;
так само шрифт і так успадковується з боді, зайвве

2024-12-20 00:28 UTC, bonny-art commented on src/partials/about.html
> +<section class="about" id="about">
видали зміни, бо будуть конфлікти

2024-12-20 00:28 UTC, bonny-art commented on src/partials/contact.html
> +<section class="contact" id="contact">
видали зміни, бо будуть конфлікти

2024-12-20 00:28 UTC, bonny-art commented on src/partials/lessons.html
> +<section class="lessons section" id="lessons">
видали зміни, бо будуть конфлікти

2024-12-20 00:28 UTC, bonny-art commented on src/partials/teachers.html
> +<section class="teachers" id="teachers">
видали зміни, бо будуть конфлікти

2024-12-20 00:28 UTC, bonny-art commented on src/partials/footer.html
> +      <nav class="footer-nav">
в середину нав потім імпортуєш відповідний компонент та передаш значення змінної (подивишся яке у файлі компоненту у коменті)

2024-12-20 00:28 UTC, bonny-art commented on src/partials/footer.html
> +      <ul class="socials-list footer-socials-list">
коли буде готовий компонент, також замість цього коду імпортуєш сюда компонент із змінною, що буде означати його розташування у футері

2024-12-20 04:06 UTC, MarynaKip commented on src/css/components/footer.css
> +  gap: 17px;
done. thanks!

2024-12-20 04:22 UTC, MarynaKip commented on src/css/components/footer.css
> +  margin-bottom: 31px;
sometimes it is difficult to catch the right value. Thanks for the review and comments. I am measuring using rectangles. And you?

2024-12-20 04:23 UTC, MarynaKip commented on src/css/components/footer.css
> +  padding: 65px 0;
updated

2024-12-20 04:54 UTC, MarynaKip commented on src/css/components/footer.css
> +  justify-content: space-between;
updated

2024-12-20 04:54 UTC, MarynaKip commented on src/partials/contact.html
> +<section class="contact" id="contact">
id is needed for navigation

2024-12-20 04:55 UTC, MarynaKip commented on src/partials/lessons.html
> +<section class="lessons section" id="lessons">
id is needed for navigation. When user press to "Our lessons" it should be navigated to lessons section

2024-12-20 04:55 UTC, MarynaKip commented on src/partials/teachers.html
> +<section class="teachers" id="teachers">
the same

2024-12-20 04:57 UTC, MarynaKip commented on src/partials/footer.html
> +      <nav class="footer-nav">
?

2024-12-20 05:00 UTC, MarynaKip commented on src/partials/footer.html
> +      <ul class="socials-list footer-socials-list">
if you are talking about the separate component - then maybe the component's owner can do all the staff connected with the component? Or please let me know once it is ready

2024-12-20 05:15 UTC, MarynaKip commented on src/partials/footer.html
> +      <p>©2023  English Excellence. All rights reserved.</p>
? What do you mean?

2024-12-20 05:26 UTC, MarynaKip commented on src/partials/footer.html
> +      <p>©2023  English Excellence. All rights reserved.</p>
updated

2024-12-20 13:45 UTC, bonny-art requested changes

2024-12-20 13:45 UTC, bonny-art commented on src/partials/contact.html
> +<section class="contact" id="contact">
нехай ід додасть той, хто робить цю секцію. так буде простіше, ніж 4 людини будуть вирішувати конфлікт....

2024-12-20 13:45 UTC, bonny-art commented on src/partials/about.html
> +<section class="about section" id="about">
нехай ід додасть той, хто робить цю секцію. так буде простіше, ніж 4 людини будуть вирішувати конфлікт....

2024-12-20 13:45 UTC, bonny-art commented on src/partials/lessons.html
> +<section class="lessons section" id="lessons">
нехай ід додасть той, хто робить цю секцію. так буде простіше, ніж 4 людини будуть вирішувати конфлікт....

2024-12-20 13:45 UTC, bonny-art commented on src/partials/teachers.html
> +<section class="teachers" id="teachers">
нехай ід додасть той, хто робить цю секцію. так буде простіше, ніж 4 людини будуть вирішувати конфлікт....

2024-12-20 13:45 UTC, bonny-art commented on src/partials/footer.html
> +      <nav class="footer-nav">
у нас вже майже є окремий компонент з пунктами навігації, який має використовуватись у 3 місцях: хедер, мобільне меню та футер. коли він буде повністю готовий .то просто імпортуєш його сюди в середину nav .footer-nav

те саме буде і із соціальними мережами.

2024-12-20 13:45 UTC, bonny-art commented on src/partials/footer.html
> +      <ul class="socials-list footer-socials-list">
так, я тобі скажу, коли він буде готовий

2024-12-20 13:45 UTC, bonny-art commented on src/css/components/footer.css
> +    padding-left: 28px;
перероби через марджин. так як це має бути відстань від сусіднього елемента, а не розширення розміру поточного.

2024-12-20 13:45 UTC, bonny-art commented on src/css/components/footer.css
> +    padding-left: 20px;
перероби через марджин. так як це має бути відстань від сусіднього елемента, а не розширення розміру поточного.

2024-12-20 13:45 UTC, bonny-art commented on src/css/components/footer.css
> +  font-family: Manrope, sans-serif;
чому не прибераєш?

2024-12-20 13:45 UTC, bonny-art commented on src/css/components/footer.css
> +  color: white;
білий колір також через змінну зроби

2024-12-20 13:45 UTC, bonny-art commented on src/partials/footer.html
> +      <nav class="footer-nav">
так само дамо знати, коли буде готовий та ти зможеш замінити

2024-12-20 19:35 UTC, MarynaKip commented on src/css/components/footer.css
> +  color: white;
done

2024-12-20 19:38 UTC, MarynaKip commented on src/css/components/footer.css
> +  letter-spacing: -2%;
done

2024-12-20 19:41 UTC, MarynaKip commented on src/css/components/footer.css
> +  font-family: Manrope, sans-serif;
done

2024-12-20 19:42 UTC, MarynaKip commented on src/partials/about.html
> +<section class="about" id="about">
done

2024-12-20 19:43 UTC, MarynaKip commented on src/partials/contact.html
> +<section class="contact" id="contact">
done

2024-12-20 19:43 UTC, MarynaKip commented on src/partials/teachers.html
> +<section class="teachers" id="teachers">
done

2024-12-21 01:04 UTC, bonny-art approved these changes

2024-12-21 01:04 UTC, merged