Teachers
bonny-art/code-crafters-tp-02 pull request #16
Opened 2024-12-21 02:19 UTC by Serhii-Palamarchuk

2024-12-21 04:00 UTC, bonny-art commented on src/css/components/teachers.css
> +.teacher-list {
коли в розмітці додаш класи кард-сет та кард-сет айтем (написала там нижче), то тут все, що стосуться флексів можна буде прибрати, лише за потреби перевизначити змінні.

2024-12-21 04:01 UTC, bonny-art commented on src/css/components/teachers.css
> +  .teacher-list {
.teacher-list {
    display: flex;
    align-items: flex-start;
    flex-wrap: wrap;
    justify-content: center;
    gap: 32px;
  }

на таблеті не працює твій флекс.

подивись, що я писала тбі в ХТМЛ на тег з цим класом.

зайве прибери

2024-12-21 04:02 UTC, bonny-art commented on src/css/components/teachers.css
> +  .teacher-card {
.teacher-card {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 16px;

це все дублюється, не потрібно

2024-12-21 04:05 UTC, bonny-art commented on src/css/components/teachers.css
> +      width: 272px;
width: 272px;
ширина тексту і так обмежується шириною картки. не потрібно

2024-12-21 04:05 UTC, bonny-art commented on src/css/components/teachers.css
> +    h2 {
h2 {
      width: 832px;
      font-size: 40px;
      line-height: 48px;
      letter-spacing: -0.8px;
    }

    p {
      width: 709px;
      color: rgba(18, 20, 23, 0.5);
      text-align: center;
      font-family: Manrope;
      font-size: 18px;
      font-style: normal;
      font-weight: 400;
      line-height: 30px; /* 166.667% */
      margin: 0 auto 40px;
      text-align: center;
    }

прибрати повністю

2024-12-21 04:07 UTC, bonny-art commented on src/css/components/teachers.css
> +    height: 318px;
height: 318px;
прибрати

коли додаш кард сет - прибери все, що стосується флексів. пр ипотребі перевизнач змінні.

те, що дублюється з попередніх розмірів пристроїв - також прибери

flex-shrink: 0; - не потрібне у тебе взагалі ніде

2024-12-21 04:08 UTC, bonny-art commented on src/css/components/teachers.css
> +  .teacher-card {
.teacher-card {
    display: flex;
    height: 318px;
    flex-direction: column;
    align-items: center;
    gap: 16px;

те, що дублюється з попередніх правил на картку - прибери. висоту задай, але через мін-хайт. бо якщо раптом тексту буд більше, то як у тебе він почне вилазити

2024-12-21 04:09 UTC, bonny-art commented on src/css/components/teachers.css
> +    p {
p {
      width: 232px;
      flex-shrink: 0;
      color: rgba(18, 20, 23, 0.5);
      text-align: center;
      font-family: Manrope;
      font-size: 16px;
      font-style: normal;
      font-weight: 400;
      line-height: 24px; /* 150% */
    }

ширину прибери, що успадковується з боді - приберию що успадковується з менших пристроїв - прибери.

2024-12-21 16:50 UTC, Serhii-Palamarchuk commented on src/css/components/teachers.css
> +  img {
огортаю img -> div і роблю стиль border-radius: 50%; overflow: hidden;

2024-12-21 18:44 UTC, Serhii-Palamarchuk reviewed
thanks! done

2024-12-21 22:21 UTC, bonny-art requested changes
Написала тобі в слек. спочатку прочитай там.

2024-12-22 15:42 UTC, bonny-art approved these changes

2024-12-22 15:42 UTC, merged